### ISSUE TITLE
Highlight stays on in preview when "startUnchecked=true" on sq-preview-entity-facet

### ISSUE THREAD

**Issue by akewea** [sinequa/sba-angular#12] opened 2020-11-13 09:12 UTC
Entities init highlighted in preview even if "startUnchecked" is true on sq-preview-entity-facet component.
This is due to :
https://github.com/sinequa/sba-angular/blob/15412c76f7b7da39ef63ff2b9089d80726e4a66c/projects/components/preview/bootstrap/preview-entity-facet/preview-entity-facet.component.ts#L104

It should be : `if(this.hidden.get(val.value)){ ` as `this.hidden` is a Map.

**Comment by ericleib** [comment] 2020-11-13 09:22
Thank you for spotting this. Will you submit a Pull Request?

**Comment by akewea** [comment] 2020-11-13 09:55
I'm not configured for this yet, but I can do it later if needed.

**Comment by ericleib** [comment] 2020-11-13 10:07
OK, I'm fixing the bug in our internal codebase, but it will only get published here upon release (with Sinequa 11.5, towards the end of the year).

**Comment by Guillaume-Developer** [comment] 2021-01-21 06:38
I have found a similar issue to this but I'm not sure if it's related. When opening the document preview, but with the left side panel closed, the entities stay highlighted in the preview panel, even if they were configured as "startUnchecked=true".
I think that the problem is not about the map but maybe the fact that if the left panel is not opened by default, then the entities left facet is not constructed, meaning that the "startUnchecked" is not applied and the entities are not deactivated in the preview. What do you think?

(Should I open a new issue for this?)

**Comment by ericleib** [comment] 2021-01-22 10:20
Fixed in Sinequa 11.5, closing the issue.

**Closed by ericleib** 2021-01-22 10:20 UTC
